version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ticket-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ticket-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - ticket-network

  user-service:
    build:
      context: ../../user-service
    container_name: user-service
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USERNAME: appuser
      DB_PASSWORD: apppassword
      JWT_SECRET: TicketBooking_JWT_Secret_Key_2026_Min_32_Chars_Long!!!
      JWT_EXPIRATION: 3600000
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - ticket-network

  movie-service:
    build:
      context: ../../movie-service
    container_name: movie-service
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USERNAME: appuser
      DB_PASSWORD: apppassword
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - ticket-network

  booking-service:
    build:
      context: ../../booking-service
    container_name: booking-service
    depends_on:
      - mysql
      - kafka
    environment:
      DB_HOST: mysql
      DB_USERNAME: appuser
      DB_PASSWORD: apppassword
      JWT_SECRET: TicketBooking_JWT_Secret_Key_2026_Min_32_Chars_Long!!!
      JWT_EXPIRATION: 3600000
      KAFKA_SERVERS: kafka:9092
      SERVER_PORT: 8083
      USER_SERVICE_URL: http://user-service:8081/user-service
      MOVIE_SERVICE_URL: http://movie-service:8082/movie-service
    ports:
      - "8083:8083"
    networks:
      - ticket-network

  notification-service:
    build:
      context: ../../notification-service
    container_name: notification-service
    depends_on:
      - kafka
    environment:
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: shrivastava.sopan@gmail.com
      MAIL_PASSWORD: bhtmzkqxdpvuocur
      KAFKA_SERVERS: kafka:9092
      SERVER_PORT: 8084
    ports:
      - "8084:8084"
    networks:
      - ticket-network

volumes:
  mysql_data:

networks:
  ticket-network:
    driver: bridge
